### ISSUE TITLE
Message rejection when timestamps are equal

### ISSUE THREAD

**Issue by realbigsean** [ethereum/builder-specs#26]
https://github.com/ethereum/builder-specs/blob/e602513bd5be4b8f0cc799af2c25e95049c2036e/apis/builder/validators.yaml#L9

The above validation results in duplicates of valid messages returning: `{"code":400,"message":"invalid timestamp"}`

I was under the impression registrations needed to be re-signed infrequently, and the once per epoch registration we are sending would be a duplicate.

This timestamp requirement also creates a re-signing once per epoch requirement (or however frequently we re send registrations), which could add a lot of load for a client running a lot of validators.

**Comment by ralexstokes** [comment]
also #24
