### ISSUE TITLE
How long should validators wait for a payload from a builder?

### ISSUE THREAD

**Issue by jtraglia** [ethereum/builder-specs#35]
I've been looking at Teku's builder endpoint recently. After sending the signed blinded block to the builder, [Teku will wait 8 seconds](https://github.com/ConsenSys/teku/blob/129bc7f336905c67b1117a4803c1daf0696c3b81/ethereum/executionclient/src/main/java/tech/pegasys/teku/ethereum/executionclient/rest/RestExecutionBuilderClient.java#L145-L152) for a payload before erroring out. Just to be clear, it will not fallback to the local payload here; it's too late for that. I'm wondering if that is an appropriate value and/or if we should define a timeout for this in the spec. I think that 8 seconds makes sense. In the spec, I only see a timeout for getting the payload header.

These are [all of the builder timeouts defined in Teku](https://github.com/ConsenSys/teku/blob/ce6e13e32f2c5029aa05895f400c00a9c72a3f38/ethereum/spec/src/main/java/tech/pegasys/teku/spec/config/Constants.java#L47-L54):

```java
Duration EL_BUILDER_CALL_TIMEOUT = Duration.ofSeconds(8);
Duration EL_BUILDER_STATUS_TIMEOUT = Duration.ofSeconds(1);
Duration EL_BUILDER_REGISTER_VALIDATOR_TIMEOUT = Duration.ofSeconds(8);
Duration EL_BUILDER_GET_HEADER_TIMEOUT = Duration.ofSeconds(1);
Duration EL_BUILDER_GET_PAYLOAD_TIMEOUT = Duration.ofSeconds(8);
```

**Comment by ralexstokes** [comment]
the honest behavior is here: https://github.com/ethereum/builder-specs/blob/main/specs/validator.md#relation-to-local-block-building

I will need to look at the code to see if this 8 seconds corresponds to what we have spec'd as 1 second however no one has done any profiling on this 1 second value so its up for debate

**Comment by ralexstokes** [comment]
another thing to note: it is still important for the proposer to be able to get the payload and assemble a complete `SignedBeaconBlock` but assumptions for this spec is that there are other incentives at play to ensure that builders release the full `SignedBeaconBlock` themselves, likely even before the proposer gets a chance to do so (and the default case is that you have both actors executing redundant actions here)

**Comment by jtraglia** [comment]
Hey @ralexstokes thanks for the reply. Do you have a source for this? Is it somewhere in the specs?

> blocks should be published on mainnet by 4 seconds after the start of the slot

And yes, your understandings check out. I put some links in the issue so that you didn't have to find this stuff yourself. So should the validator only actually wait 4 seconds for an execution payload from the builder? Should this be in the specs?

One of my concerns is a malicious builder that will send execution payload headers but never send execution payloads. It might also be worth having this timeout in the spec just so implementations remember to have a timeout there. It would be embarrassing if there were no timeout at all and it essentially shuts down a validator if a builder doesn't respond.

**Comment by ralexstokes** [comment]
@jtraglia so an honest proposer should broadcast at the "start" of the slot

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#block-proposal

let's allow for some small delay to build and broadcast the block.

this is the earliest they could propose (and note there is a small "clock disparity" allowance at the gossip layer and most (all?) clients queue early messages).

what about the latest?

the only real bound I see is this condition from the p2p spec:

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#beacon_block

> [IGNORE] The block is from a slot greater than the latest finalized slot -- i.e. validate that signed_beacon_block.message.slot > compute_start_slot_at_epoch(state.finalized_checkpoint.epoch) (a client MAY choose to validate and store such blocks for additional purposes -- e.g. slashing detection, archive nodes, etc).

but this has to be balanced against the fork choice

you need a majority of the validators to eventually attest to a chain that contains your late block.

and the usual working assumption is that if you miss the "attestation deadline" for a slot (when validators for a given slot should broadcast their attestations) then the next block will have more stake weight in the fork choice (it would just take literally 1 Gwei to bias the fork choice away) so your late block will be orphaned from the chain

if we look at the spec for this "attestation deadline", we see it is `SECONDS_PER_SLOT / INTERVALS_PER_SLOT` (4 seconds on mainnet)

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#attesting

**Comment by ralexstokes** [comment]
> So should the validator only actually wait 4 seconds for an execution payload from the builder?

we have an even tighter condition now of 1 second -- the `BUILDER_PROPOSAL_DELAY_TOLERANCE` I linked to above

**Comment by ralexstokes** [comment]
> One of my concerns is a malicious builder that will send execution payload headers but never send execution payloads. It might also be worth having this timeout in the spec just so implementations remember to have a timeout there. It would be embarrassing if there were no timeout at all and it essentially shuts down a validator if a builder doesn't respond.

yeah I think the biggest counterparty risk a proposer takes using the external builder network at the moment is some kind of availability failure. this is part of why we have an intermediate role -- the relay -- that functions as an "availability escrow"

and there are a lot of things we could do to enhance the availability guarantees -- e.g. all relays could gossip to one another, they can all be connected to the beacon block gossip network to disseminate the block themselves.

I think we will definitely see an off-chain reputation system based on data availability and I expect a relay with bad performance will not be chosen by proposers relative to those that have a good history.

I don't really follow the last part? If a validator client cannot get the full payload then as far as validating goes, the client just moves on to the next set of duties...

**Comment by jtraglia** [comment]
Thank you for the resources and explaining!

> we have an even tighter condition now of 1 second -- the BUILDER_PROPOSAL_DELAY_TOLERANCE I linked to above

So this is actually the timeout for receiving a `SignedBuilderBid` (with an execution payload header), not an `ExecutionPayload`. I was specifically asking about the latter, as Teku has chosen a somewhat arbitrary timeout of 8 seconds for this. But I'm not even sure this matters. I'm wondering if there should be an additional timeout in the spec.

> I don't really follow the last part? If a validator client cannot get the full payload then as far as validating goes, the client just moves on to the next set of duties...

This isn't really a concern, but if there is no timeout at all (unlikely) and the validator isn't multithreaded (unlikely), the validator would forever wait for an execution payload from the external builder. Like a program blocked on a `recv` call. It could be less serious than this but still harmful. Let's say without a timeout, the validator will wait 30 seconds before giving up. If an external builder chooses not to send an `ExecutionPayload`, it could prevent the validator from performing its other duties for 30 seconds.

**Comment by ralexstokes** [comment]
yeah I personally think if a validator client implementation has that behavior then it is simply a bug and should be fixed :)

I don't think we want any task in the validator client to block any other task

and for this reason I don't really see the value in mandating something in the spec to this effect

if a particular implementation needs to mandate some overall timeout, that's fine but imo its an implementation detail and I'd rather leave the design space open as far as writing a spec goes
