### ISSUE TITLE
Swagger UI broke w/ `v0.3.0`

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/builder-specs#71]
not sure what is going on but I think something broke the rendering https://ethereum.github.io/builder-specs/

in this commit: https://github.com/ethereum/builder-specs/commit/58e2c66e6fecccbe14c5ddf718ebc68a3c6a03eb

**Comment by fredriksvantes** [comment]
Appears to be working here, the first time loading the page just takes a while to complete

![builder-api](https://user-images.githubusercontent.com/84518844/231109547-cf6a21b9-7277-40d9-a0ca-d71e74bc6ed0.png)

**Comment by ralexstokes** [comment]
yeah I've seen spotty performance... but there is also that `invalid` tag at the bottom of your screenshot

I don't know enough about how this UI is served to say more...

**Comment by ralexstokes** [comment]
trying to fix this by matching the https://github.com/ethereum/beacon-APIs config, otherwise will just let it be
